/* eslint-disable react/function-component-definition */
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import logoBlue from '../lib/assets/logos/logo-blue.png';

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <Image className={styles.logo} src={logoBlue} width={250} height={250} />
      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Blue Fire!</a>
      </h1>

      <p className={styles.description}>
        Your one stop shop for all your menu needs!
      </p>

      <div className={styles.grid}>
        <Link href="/GraphqlMenu">
          <a className={styles.card}>
            <h2>GraphQL Menu &rarr;</h2>
            <p>
              Get our freshest burgers called through our latest GraphQL API
            </p>
          </a>
        </Link>
        <Link href="/RestMenu">
          <a className={styles.card}>
            <h2>REST Menu &rarr;</h2>
            <p>
              Kick back with a pizza made by our best chefs and called through
              our REST API
            </p>
          </a>
        </Link>
      </div>
    </main>
  </div>
);

export default Home;
